FROM openjdk:17-jdk-alpine

#naveen
#FROM eclipse-temurin:11-alpine
#ARG JAR_FILE=target/*jar
#ENV MONGODB_USERNAME=arunbalaji5005
#ENV MONGODB_PASSWORD=UCR8ee9aISJY9Fom
ARG USERNAME
ARG PASSWORD
ENV MONGO_USERNAME=${USERNAME}
ENV MONGO_PASSWORD=${PASSWORD}
EXPOSE 8080
COPY target/services-0.0.1-SNAPSHOT.jar user.jar
ENTRYPOINT ["java","-jar","user.jar"]
