FROM openjdk:17-jdk-alpine

#naveen
#FROM eclipse-temurin:11-alpine
#ARG JAR_FILE=target/*jar
ARG USERNAME
ARG PASSWORD
ENV MONGODB_USERNAME=${USERNAME}
ENV MONGODB_PASSWORD=${PASSWORD}
EXPOSE 8081
COPY target/services-0.0.1-SNAPSHOT.jar transaction.jar
ENTRYPOINT ["java","-jar","transaction.jar"]
